#!/bin/bash
wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print int($2*100)}'
pactl subscribe | grep --line-buffered "sink" | while read -r _; do
    wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print int($2*100)}'
done
